### ISSUE TITLE
desktop - What's your run command?

### ISSUE THREAD

**Issue by johnjelinek** [oddlid/dockerfiles#1]
I didn't see vnc installed or any x11 forwarding instructions. Can you add some documentation on how you recommend connecting to the container?

**Comment by oddlid** [comment]
The way I've used this image, is by having a minimal Debian installation with Xorg and docker on my laptop. I then log in on the console and run "startx" that only opens X and a terminal, no WM. I then from that terminal run something like this:
```
/usr/bin/docker run \
                --privileged \
                --device /dev/snd \
                --device /dev/tty0 \
                --net="host" \
                -v /etc/localtime:/etc/localtime:ro \
                -v /etc/passwd:/etc/passwd:ro \
                -v /etc/shadow:/etc/shadow:ro \
                -v /etc/group:/etc/group:ro \
                -v /etc/sudoers:/etc/sudoers:ro \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                -v $HOME:$HOME \
                -e DISPLAY=unix${DISPLAY} \
                -e TERMINAL=xfce4-terminal \
                --rm \
                -it \
                -u $(whoami) \
                -w $HOME \
                oddlid/arch-desktop /usr/bin/i3
```
Actually I have this in a script where `/usr/bin/i3` is replaced by `$*` so I can start whatever I want this way.
