### ISSUE TITLE
The Dockerfile should install python3 to have the docker-cli working.

### ISSUE THREAD

**Issue by pdemaret** [oddlid/dockerfiles#2]
I refer here to the docker files/dropbox scripts.

Well, thank you for this minimal dropbox install under docker.
It appears that the latest dropbox install now requires python3 to run the cli utilities. 
I installed your Dockerfile and modified the line 22 from python2.7 to python3 and it all worked.

Thank you again,

Patrick.

**Comment by oddlid** [comment]
Thanks for letting me know!
I've updated the Dockerfile to install python3 now.
